baseURL: "https://www.scottlowry.net/"
languageCode: "en-us"
title: "ScottLowry.net"
theme: "PaperMod"

taxonomies:
  tag: tags
  series: series

params:
  defaultTheme: "auto"
  disableThemeToggle: false
  ShowReadingTime: false
  ShowShareButtons: true
  ShowPostNavLinks: false
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: false
  ShowWordCount: false
  ShowFullTextinRSS: false
  ShowToc: true
  hideFooter: false
  
  assets:
    favicon: "/favicon.ico"
    favicon16x16: "/favicon-16x16.png"
    favicon32x32: "/favicon-32x32.png"
    apple_touch_icon: "/apple-touch-icon.png"
    safari_pinned_tab: "/safari-pinned-tab.svg"

  socialIcons:
      - name: "linkedin"
        url: "https://www.linkedin.com/in/scott-m-lowry/"
      - name: "github"
        url: "https://www.github.com/scottlowry"
      - name: "email"
        url: "mailto:Scott@ScottLowry.net"

  homeInfoParams:
    Title: "Welcome to my blog!"
    Content: "This is where I write about my experiences and thoughts on technology, security, and automation."

  mainSections:
    - posts
    - series

menu:
  main:
    - identifier: "Archive"
      name: "Archive"
      url: "/archives/"
      weight: 1
    - identifier: "Series"
      name: "Series"
      url: "/series/"
      weight: 2
    - identifier: "Tags"
      name: "Tags"
      url: "/tags/"
      weight: 3
    - identifier: "Search" 
      name: "Search"
      url: "/search/"
      weight: 4
    - identifier: "Home"
      name: "Home"
      url: "/"
      weight: 5

search:
  enable: true

outputs:
  home:
    - HTML
    - RSS
    - JSON 